version: '3.2'
services:
  dns_server:
    container_name: dns_server
    build: dns/.
    depends_on:
      - test_app
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["./wait-for-it.sh", "test_app:80", "-t","180", "--", "./setup-and-run.sh"]
  test_app:
    container_name: test_app
    build: 
      context: test_app/
      dockerfile: local.Dockerfile
  driver:
    container_name: driver
    build: 
      context: .
      dockerfile: local.Dockerfile
    depends_on:
      - test_app
      - dns_server
    dns:
      - dns_server
    environment:
      - RUN_ENV=local
    volumes:
      - ./testcases:/testcases/
      - ./.env:/.env
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["./wait-for-it.sh", "dns_server:53", "-t","180", "--","bash","./startup.sh","${TESTCASES}"]


    
    


